### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by rnyberg** [tjmehta/atom-term#27]
[Enter steps to reproduce below:]

1. open terminal in a tab
2. run "svn commit" which should open nano with the comment dialog
3. error

**Atom Version**: 0.174.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [term](https://github.com/tjmehta/atom-term) package, v0.2.2

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /home/reijo/.atom/packages/term/node_modules/term.js/src/term.js:1479

TypeError: Cannot set property '0' of undefined
  at Terminal.write (/home/reijo/.atom/packages/term/node_modules/term.js/src/term.js:1479:55)
  at ReadStream.ondata (_stream_readable.js:539:20)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at ReadStream.Readable.push (_stream_readable.js:125:10)
  at TTY.onread (net.js:522:20)

```

### Commands

```
     -0:43.4 command-palette:toggle (atom-text-editor.editor)
  2x -0:42.7 core:backspace (atom-text-editor.editor.mini)
  3x -0:40.4 core:move-down (atom-text-editor.editor.mini)
     -0:36.3 core:confirm (atom-text-editor.editor.mini)
     -0:36.3 terminal-panel:new (atom-text-editor.editor)
     -0:34.5 editor:consolidate-selections (atom-text-editor.editor)
     -0:34.5 core:cancel (atom-text-editor.editor)
     -0:31.7 command-palette:toggle (atom-text-editor.editor)
     -0:28.9 core:confirm (atom-text-editor.editor.mini)
     -0:28.9 term2:pipe-path (atom-text-editor.editor)
     -0:12.0 command-palette:toggle (atom-text-editor.editor)
  2x -0:10.5 core:backspace (atom-text-editor.editor.mini)
  2x -0:08.7 core:move-down (atom-text-editor.editor.mini)
  4x -0:02.8 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 term:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".svn",
      "gw"
    ],
    "disabledPackages": [
      "file-icons",
      "terminal-panel"
    ],
    "themes": [
      "seti-ui",
      "seti-monokai"
    ],
    "projectHome": "/home/reijo/projects",
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.2
atom-color-highlight, v3.0.5
atom-terminal, v0.6.0
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
color-picker, v1.4.4
emmet, v2.3.2
file-types, v0.3.0
jshint, v1.2.0
linter, v0.10.0
livereload, v0.2.0
minimap, v3.5.6
open-last-project, v0.1.1
project-colorize, v0.1.0
project-manager, v1.15.0
remember-session, v0.5.1
seti-monokai, v0.3.1
seti-ui, v0.6.1
term, v0.2.2
term2, v0.9.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by francesconero** [comment]
+1
