### ISSUE TITLE
Uncaught Error: ioctl(2) failed.

### ISSUE THREAD

**Issue by wjordan213** [tjmehta/atom-term#29]
[Enter steps to reproduce below:]
using the better snap tool app, made it so my atom screen took up half of my computer screen. That was when the error was thrown. I did not have any open terms at that time.

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [term](https://github.com/tjmehta/atom-term) package, v0.2.2

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /Users/wjordan213/.atom/packages/term/node_modules/pty.js/lib/pty.js:331

Error: ioctl(2) failed.
  at Error (native)
  at Terminal.resize (/Users/wjordan213/.atom/packages/term/node_modules/pty.js/lib/pty.js:331:7)
  at TermView.resizeToPane (/Users/wjordan213/.atom/packages/term/lib/TermView.js:115:12)
  at delayed (/Users/wjordan213/.atom/packages/term/node_modules/debounce/index.js:19:14)

```

### Commands

```
     -2:39.5 term:open-split-right (atom-text-editor.editor.is-focused)
     -2:15.2 pane:close (div.terminal)
     -2:07.7 term:open-split-right (atom-text-editor.editor.is-focused)
     -2:03.2 pane:close (div.terminal)
  2x -2:01.2 core:close (atom-text-editor.editor.is-focused)
     -1:49.9 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -1:44.8 core:confirm (atom-text-editor.editor.mini)
     -1:44.1 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -1:43.0 core:backspace (atom-text-editor.editor.mini)
  2x -1:42.2 core:move-down (atom-text-editor.editor.mini)
     -1:39.0 core:confirm (atom-text-editor.editor.mini)
     -1:13.5 core:save (atom-text-editor.editor.is-focused)
     -0:57.9 core:move-left (atom-text-editor.editor.is-focused)
 12x -0:57.3 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:55.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:53.8 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jumpy",
      "emmet"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.4
atom-lint, v0.20.1
indentation-jumper, v0.1.1
linter, v0.12.0
linter-csslint, v0.0.11
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
term, v0.2.2

# Dev
No dev packages
```

**Comment by daiweilu** [comment]
+1

**Comment by josephlewis42** [comment]
More debugging is better!

This time on linux mint, snapping to the side of the screen caused the warning. A terminal was previously open, but all tabs had been closed at this point.

Prior to a terminal being launched, snapping works. While the terminal is launched it still works without error, after being closed it throws the error.


**Atom Version**: 0.188.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [term](https://github.com/tjmehta/atom-term) package, v0.2.2

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /home/joseph/.atom/packages/term/node_modules/pty.js/lib/pty.js:331

Error: ioctl(2) failed.
  at Error (native)
  at Terminal.resize (/home/joseph/.atom/packages/term/node_modules/pty.js/lib/pty.js:331:7)
  at TermView.resizeToPane (/home/joseph/.atom/packages/term/lib/TermView.js:115:12)
  at delayed (/home/joseph/.atom/packages/term/node_modules/debounce/index.js:19:14)

```

### Commands

```
     -2:01.9 core:confirm (atom-text-editor.editor.mini)
     -2:01.9 term:open (atom-text-editor.editor.is-focused)
     -1:48.2 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:46.9 core:backspace (atom-text-editor.editor.mini)
     -1:46.0 core:confirm (atom-text-editor.editor.mini)
     -1:46.0 application:zoom (atom-text-editor.editor.is-focused)
     -1:44.6 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -1:43.0 core:backspace (atom-text-editor.editor.mini)
  3x -1:38.7 core:move-down (atom-text-editor.editor.mini)
     -1:38.1 core:move-up (atom-text-editor.editor.mini)
     -1:37.8 core:confirm (atom-text-editor.editor.mini)
     -1:37.8 window:reset-font-size (atom-text-editor.editor.is-focused)
  5x -1:29.7 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
  3x -1:26.7 window:increase-font-size (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 13x -1:25.9 window:decrease-font-size (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -1:21.6 window:increase-font-size (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-clang",
      "linter-clang",
      "gocode",
      "godef",
      "linter",
      "terminal-runner",
      "base-n",
      "color-picker",
      "toggle-invisibles",
      "save-session",
      "switch-header-source",
      "autocomplete-plus",
      "go-plus"
    ],
    "projectHome": "/home/joseph/Projects",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.6
minimap, v4.7.6
term, v0.2.2

# Dev
No dev packages
```

**Comment by kane-thornwyrd** [comment]
Moving the Atom window…

**Atom Version**: 1.0.2
**System**: "Fedora release
**Thrown From**: [term](https://github.com/tjmehta/atom-term) package, v0.2.3


### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /home/jctherond/.atom/packages/term/node_modules/pty.js/lib/pty.js:321

Error: ioctl(2) failed.
  at Error (native)
  at Terminal.resize (/home/jctherond/.atom/packages/term/node_modules/pty.js/lib/pty.js:321:7)
  at TermView.resizeToPane (/home/jctherond/.atom/packages/term/lib/TermView.js:115:12)
  at delayed (/home/jctherond/.atom/packages/term/node_modules/debounce/index.js:19:14)

```

### Commands

```
     -4:11.9.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "pairing-chat",
      "backbonejs-snippets",
      "pairing-chat",
      "backbonejs-snippets",
      "pairing-chat",
      "node-resolver"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-backbone, v0.6.1
autocomplete-modules, v1.0.0
color-picker, v2.0.11
docblockr, v0.7.3
file-type-icons, v0.7.0
gulp-snippets, v0.6.1
jshint, v1.3.9
linter, v1.2.4
minimap, v4.12.1
monokai, v0.15.0
motepair, v0.20.0
project-manager, v1.15.11
project-sidebar, v1.3.0
project-view, v0.1.2
save-session, v0.15.7
svn, v0.0.7
term, v0.2.3
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by niahmiah** [comment]
I get this on OS X (yosemite) each time I enter or exit full screen

**Comment by vantang** [comment]
+1
