### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by horiuchi** [tjmehta/atom-term#45]
[Enter steps to reproduce below:]

1. exec `git log --graph --oneline --decorate --all` on zsh

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [term](https://github.com/tjmehta/atom-term) package, v0.2.3

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of undefined

```
At /Users/horiuchihiroki/.atom/packages/term/node_modules/term.js/src/term.js:1293

TypeError: Cannot set property 'innerHTML' of undefined
  at Terminal.refresh (/Users/horiuchihiroki/.atom/packages/term/node_modules/term.js/src/term.js:1293:32)
  at Terminal.reset (/Users/horiuchihiroki/.atom/packages/term/node_modules/term.js/src/term.js:2915:8)
  at Terminal.setMode (/Users/horiuchihiroki/.atom/packages/term/node_modules/term.js/src/term.js:3765:16)
  at Terminal.setMode (/Users/horiuchihiroki/.atom/packages/term/node_modules/term.js/src/term.js:3658:12)
  at Terminal.write (/Users/horiuchihiroki/.atom/packages/term/node_modules/term.js/src/term.js:1987:18)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -8:25.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -5:24.5.0 core:paste (atom-text-editor#linter-tslint.tslintExecutablePath.editor.mini.is-focused)
  2x -4:12 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -3:51.2.0 editor:move-to-first-character-of-line (atom-text-editor#linter-tslint.tslintExecutablePath.editor.mini.is-focused)
     -3:50.6.0 editor:move-to-end-of-screen-line (atom-text-editor#linter-tslint.tslintExecutablePath.editor.mini.is-focused)
  2x -3:50.2.0 core:move-right (atom-text-editor#linter-tslint.tslintExecutablePath.editor.mini.is-focused)
  2x -3:15.2.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:43.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:37.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:37.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:32.3.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:23.9.0 application:new-file (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -2:14.6.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode)
     -1:19.2.0 term:open-split-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:42.8.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:30.5.0 term:open-split-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.2.3
autocomplete-paths, v1.0.2
color-picker, v2.0.11
file-icons, v1.5.8
highlight-selected, v0.10.1
linter, v1.2.4
linter-tslint, v0.2.3
minimap, v4.12.1
project-manager, v1.15.11
term, v0.2.3
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by rondonjon** [comment]
Same thing here after running `nano <filename>`
