### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by Exaveb** [tjmehta/atom-term#52]
Hi, This package do not install in my laptop,

**Comment by massiws** [comment]
Same issue on my Linux Mint 17.3.
Here the log output:
`> pty.js@0.3.0 install /tmp/apm-install-dir-11638-8388-109kc0b/node_modules/term/node_modules/pty.js

> node-gyp rebuild

make: ingresso nella directory "/tmp/apm-install-dir-11638-8388-109kc0b/node_modules/term/node_modules/pty.js/build"
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: uscita dalla directory "/tmp/apm-install-dir-11638-8388-109kc0b/node_modules/term/node_modules/pty.js/build"

make: g++: comando non trovato
make: **\* [Release/obj.target/pty/src/unix/pty.o] Errore 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.0-34-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11638-8388-109kc0b/node_modules/term/node_modules/pty.js
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/max/.atom/.apm/.apmrc" "--userconfig" "/home/max/.atom/.apmrc" "install" "/tmp/d-11638-8388-fhxx0q/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11638-8388-109kc0b/npm-debug.log`

**Comment by AverageComet250** [comment]
the same issue came for me on windows 10 x64. I do have cmd legacy console on by the way
